# Generated by Django 5.2 on 2025-04-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authuser",
            options={"managed": True},
        ),
    ]
